SELECT f.JUR,
 f.PARID,
 f.TAXYR,
 f.FILEYR,
 f.INVENTORY_TYPE,
 f.INVENTORY_MONTH,
 f.INVENTORY_AMT
FROM noa_pp_lat_5_inventories AS f
INNER JOIN noa_pp_lat5 AS p ON f.NOA_PP_LAT_5_ID = p.NOA_PP_LAT_5_ID 
INNER JOIN form AS gp ON p.FORM_ID = gp.FORM_ID 
WHERE gp.STATUS_ID = 3
AND f.INVENTORY_AMT > 0