SELECT f.JUR,
 f.PARID,
 f.TAXYR,
 f.CATEGORY,
 f.PPTYPE,
 f.FILEYR,
 f.YRACQD,
 f.NOUNITS,
 f.ACQUISITION_COST,
 f.EFFECTIVE_LIFE,
 f.CONSIGNER_OWNER_NAME,
 f.CONSIGNER_MAILING_ADDR,
 f.CONSIGNER_RENTAL_AMT,
 f.ITEM_DESCRIPTION,
 f.CONSIGNER_TEL_NO
FROM noa_pp_lat_5_filing AS f
INNER JOIN noa_pp_lat5 as p ON f.NOA_PP_LAT_5_ID = p.NOA_PP_LAT_5_ID
INNER JOIN form AS gp ON p.FORM_ID = gp.FORM_ID
WHERE gp.STATUS_ID = 3